# Generated by Django 5.2.17 on 2026-09-21 00:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('scholarship', 'Scholarship'), ('internship', 'Internship'), ('competition', 'Competition'), ('hackathon', 'Hackathon'), ('workshop', 'Workshop'), ('training', 'Training'), ('other', 'Other')], max_length=20)),
                ('eligibility', models.TextField(blank=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('is_remote', models.BooleanField(default=False)),
                ('source_url', models.URLField(blank=True)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('archived', 'Archived')], default='active', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['status'], name='opportuniti_status_fb4df4_idx'), models.Index(fields=['category'], name='opportuniti_categor_dd0690_idx'), models.Index(fields=['deadline'], name='opportuniti_deadlin_294f61_idx')],
            },
        ),
    ]
