# Generated by Django 5.2.17 on 2026-09-21 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=260)),
                ('summary', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True, help_text='One per line')),
                ('content', models.TextField(help_text='Sanitized HTML')),
                ('content_raw', models.TextField(blank=True, help_text='Original before sanitization for admin')),
                ('key_concepts', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='subjects.topic')),
            ],
            options={
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['status'], name='learning_le_status_901b1f_idx'), models.Index(fields=['slug'], name='learning_le_slug_185a12_idx')],
                'unique_together': {('topic', 'slug')},
            },
        ),
    ]
