# Generated by Django 5.2.17 on 2026-09-21

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.CheckConstraint(
                condition=(
                    Q(('resource__isnull', False), ('topic__isnull', True), ('opportunity__isnull', True))
                    | Q(('resource__isnull', True), ('topic__isnull', False), ('opportunity__isnull', True))
                    | Q(('resource__isnull', True), ('topic__isnull', True), ('opportunity__isnull', False))
                ),
                name='bookmark_exactly_one_target',
            ),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(
                condition=Q(('resource__isnull', False)),
                fields=('user', 'resource'),
                name='unique_user_resource_bookmark',
            ),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(
                condition=Q(('topic__isnull', False)),
                fields=('user', 'topic'),
                name='unique_user_topic_bookmark',
            ),
        ),
        migrations.AddConstraint(
            model_name='bookmark',
            constraint=models.UniqueConstraint(
                condition=Q(('opportunity__isnull', False)),
                fields=('user', 'opportunity'),
                name='unique_user_opportunity_bookmark',
            ),
        ),
    ]
