# Generated by Django 5.2.17 on 2026-09-21 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('discipline', models.CharField(help_text='e.g. Information Technology, Business', max_length=100)),
                ('icon', models.CharField(blank=True, help_text='lucide/icon name', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['slug'], name='subjects_su_slug_c60d67_idx'), models.Index(fields=['discipline'], name='subjects_su_discipl_1190d6_idx'), models.Index(fields=['status'], name='subjects_su_status_c06407_idx')],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('summary', models.TextField(blank=True)),
                ('learning_objectives', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='subjects.subject')),
            ],
            options={
                'ordering': ['order', 'title'],
                'indexes': [models.Index(fields=['slug'], name='subjects_to_slug_09284a_idx'), models.Index(fields=['status'], name='subjects_to_status_a98e95_idx')],
                'unique_together': {('subject', 'slug')},
            },
        ),
    ]
